name: CI-PHP

on:
  push:
    branches:
      - main
      - release/*
      - develop
      - github-actions
  pull_request:
    branches:
      - main
      - release/*
      - develop

jobs:
  code-standard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP Code Style (phpcs)
        uses: chindit/actions-phpcs@master

  build-and-phpunit-tests:

    runs-on: ubuntu-latest

    env:
      DB_PORT: 3306
      DB_CONNECTION: mysql
      DB_DATABASE: location_api
      DB_USERNAME: root
      DB_HOST: 127.0.0.1
      DB_PASSWORD: root

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpunit
      - name: Show versions
        run: php -v && composer -V
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Init Database
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS location_api;'
      - name: Migrate Database
        run: php artisan migrate
      - name: Build VITE Manifest
        run: npm i && npm run build
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit --testdox
